### ISSUE TITLE
Write ucs.py for an Uniform Cost Search Agent

### ISSUE THREAD

**Issue by SasankYadati** [SasankYadati/CS325-Artificial-Intelligence#7]
Looking for help to build Uniform Cost Search agent for 8puzzle environment written in `enviroment.py` in `Unit1/Classical Search`

Go through `astar.py` for an idea on coding style.

**Comment by ruthmd** [comment]
I will take this up. @SasankYadati

**Comment by SasankYadati** [comment]
Go ahead.

**Comment by SasankYadati** [comment]
Cool.
